/* data.js — portfolio content distilled from Annabelle's UX portfolio PDF */
window.PROFILE = {
  name: 'Annabelle Clark-Lepard',
  role: 'Product Design Leader',
  location: 'Toronto, Canada',
  email: 'annabelle.clarklepard@gmail.com',
  linkedin: 'www.linkedin.com/in/annabelle-clark-lepard',
  linkedinUrl: 'https://www.linkedin.com/in/annabelle-clark-lepard',
  headline: 'Designing clarity into complex systems.',
  subhead: 'I lead product design for financial, operational, and accessible platforms at scale — turning audits, data, and constraints into experiences teams trust.',
  specialties: [
    'B2B financial & operational systems',
    'Payments, registration & data-heavy workflows',
    'Design & process AI transformation',
  ],
};

window.METRICS = [
  { n: '2M+', l: 'Users guided through high-traffic events' },
  { n: '4 days', l: 'Faster merchant statements, every month' },
  { n: 'WCAG AA', l: 'Accessible design system, by default' },
];

window.EXPERTISE = [
  {
    icon: 'landmark',
    h: 'Financial Systems & Payments',
    p: 'Merchant statements, reconciliation, and billing flows where accuracy, traceability, and trust are non-negotiable.',
  },
  {
    icon: 'gauge',
    h: 'Performance & High-Stakes UX',
    p: 'Queueing, registration, and security-recovery flows that stay calm and usable under load, stress, and competitive pressure.',
  },
  {
    icon: 'megaphone',
    h: 'Client Communication & Workflow Tooling',
    p: 'Staff-facing tools for hiring and client communication — built for real volume, fast scanning, and legible status.',
  },
  {
    icon: 'sparkles',
    h: 'AI Transformation Leadership',
    p: 'Leading product teams from AI-skeptical to AI-fluent — embedding AI into delivery workflows responsibly, not just as novelty.',
  },
  {
    icon: 'search',
    h: 'Research, Analysis & Documentation',
    p: 'Turning noisy backlogs and scattered knowledge into synthesized themes, audits, and documentation teams actually use.',
  },
  {
    icon: 'layout-grid',
    h: 'Accessible Design Systems',
    p: 'Single sources of truth that bake WCAG AA into defaults — reducing friction, regressions, and rework across product and engineering.',
  },
];

window.SKILLS = [
  { h: 'Design', items: ['Product Design', 'Design Systems', 'Interaction Design', 'Accessibility (WCAG AA)', 'Prototyping', 'Mobile-first UI'] },
  { h: 'Research & Process', items: ['User Research', 'Usability Testing', 'Journey & Flow Mapping', 'Edge-case Validation', 'Project Management'] },
  { h: 'Technical', items: ['Figma', 'FigJam', 'SQL Querying', 'API Integration', 'HTML & CSS'] },
];

window.PROJECTS = [
  {
    id: 'design-system',
    tag: 'Design Systems',
    title: 'Accessible Design System as a Source of Truth',
    blurb: 'A WCAG AA-compliant system that became the shared language between design, product, and engineering.',
    discipline: 'Design systems that reduce friction, ensure consistency, and make it easier for teams to ship accessible, high-quality UX.',
    role: 'Product Designer · Project Manager',
    context: 'Figma · Mobile-first · B2B2C e-commerce',
    constraints: ['Legacy functionality', 'WCAG AA audit requirements', 'Non-technical product team', 'Lack of design resources'],
    accent: 'var(--color-teal)',
    image: 'assets/proj-design-system.png',
    imageCaption: 'Button system — primary, secondary, and contrast variants with documented states and accessibility rationale (WCAG AA).',
    solution: 'A comprehensive, WCAG AA-compliant design system serving as a shared source of truth across product, design, and development — covering every reusable component in the codebase, not just buttons, with naming and semantics matched to the code so designers, PMs, and engineers were always referencing the same thing the same way.',
    solutionPoints: [
      'Every reusable component in the codebase represented in the system — inputs, cards, alerts, navigation, and more, not just buttons — each with documented states and accessibility rationale.',
      'Component naming and semantics matched directly to the codebase, so a "primary button" or "alert banner" in Figma was unambiguously the same thing a developer saw in code.',
      'Primary button variants documented with when, why, and the key accessibility decisions behind each.',
      'Foundational colours connected to variables, with guidance on when and why each colour applies.',
    ],
    problems: [
      { who: 'The User', sub: 'E-commerce portal customers', t: 'Inconsistent UI patterns created fragmented, confusing experiences.' },
      { who: 'The Developers', sub: '', t: 'Lost time rebuilding or adapting components for every new feature.' },
      { who: 'The Product Team', sub: '', t: 'Struggled to communicate with developers without a reliable reference point.' },
      { who: 'The Business', sub: '', t: 'Growing WCAG requirements introduced real risk of non-compliance.' },
    ],
    success: [
      'A single source of truth for design, product, and engineering.',
      'Accessible components by default — WCAG AA compliant.',
      'Faster, smoother feature delivery with fewer UX regressions.',
      'Clear communication across product and development.',
    ],
    process: [
      'Audited the existing UI for inconsistencies, accessibility gaps, and legacy patterns — mapping end-to-end flows to see how components behaved in real scenarios.',
      'Defined system foundations: core components, states, patterns, typography, colour, spacing, and interaction principles built for scale and accessibility.',
      'Built the system in Figma with styles, variables, and components — every reusable component named and structured to match its counterpart in code — so consistency and accessibility were baked into defaults, not applied retroactively.',
      'Collaborated with PMs and developers to validate feasibility, align on needs, and drive adoption across teams.',
    ],
    impact: [
      'Increased PM confidence communicating priorities through a shared, reliable source of truth.',
      'Improved developer clarity with reusable components whose names and semantics matched the code, cutting translation loss between design and engineering.',
      'Reduced WCAG AA compliance risk by embedding accessibility rather than reacting to it.',
      'Freed up team time to focus on product strategy under one aligned vision.',
    ],
    challenge: 'Aligning developers and non-technical product managers on priorities, tradeoffs, and feasibility while establishing a shared system.',
    takeaway: 'Design systems align teams on more than pixels. Treated as a collaborative initiative, they create shared language, reduce friction between roles, and make accessibility and consistency the foundation a team can rely on.',
  },
  {
    id: 'merchant-statements',
    tag: 'Financial Systems',
    title: 'Integrated Payment Processing Merchant Statements',
    blurb: 'An automated, transparent merchant statement experience connecting UI, SQL data, and APIs into one coherent system.',
    discipline: 'Easy-to-use financial tools that balance accuracy, trust, and the realities of audits, reconciliation, and constraints.',
    role: 'Product Designer · Product Manager · Project Manager',
    context: 'Figma · SQL Financial Querying · API Integration · B2B',
    constraints: ['Legacy financial workflows', 'Third-party integrations', 'Data accuracy & audit requirements', 'Non-technical users'],
    accent: 'var(--color-sage)',
    image: 'assets/proj-merchant.png',
    imageCaption: 'Merchant statement portal — dated statements, fee history, and recipient management, opening the generated statement document.',
    solution: 'A fully integrated, automated merchant statement experience accessible from the user portal — connecting UI design, SQL-driven data generation, and API responses into a single, coherent system.',
    solutionPoints: [
      'Built into the portal where users already work — letting them access dated statements and edit account settings without manual intervention.',
    ],
    problems: [
      { who: 'The User', sub: 'Merchants', t: 'Limited visibility into how statement totals were calculated reduced trust and usability.' },
      { who: 'The Developers', sub: '', t: 'Manual processes and unclear data connections increased errors and slowed troubleshooting.' },
      { who: 'The Business', sub: '', t: 'Manual invoicing introduced accuracy risk, delayed revenue communication, and operational overhead.' },
    ],
    success: [
      'Clear, trustworthy merchant statements that explain financial outcomes.',
      'A shared data model aligning UI, APIs, and reconciliation logic.',
      'Automated statement generation with minimal manual intervention.',
    ],
    process: [
      'Collaborated with payment operations to map user expectations, pain points, and typical billing and reconciliation flows.',
      'Partnered with third-party and internal engineers to align API responses with clearly structured, understandable financial data.',
      'Designed the merchant-facing UI for accessing and understanding statements — focused on clarity, hierarchy, and trust.',
      'Wrote and validated SQL queries generating statement data, ensuring accuracy, traceability, and reconciliation support.',
      'Tested statement data against edge cases to validate accuracy under varied scenarios.',
    ],
    impact: [
      'Improved user trust through clearer, more transparent financial statements.',
      'Reduced troubleshooting ambiguity by aligning APIs directly to reconciliation needs.',
      'Eliminated manual errors through accurate, SQL-driven statement generation.',
      'Accelerated statement delivery by 4 days each month for faster reconciliation.',
    ],
    challenge: 'Bridging UI/UX design, data logic, and API constraints while keeping financial data accurate, explainable, and trustworthy for non-technical users.',
    takeaway: 'Designing financial products requires ownership beyond the interface. When designers engage with data and system logic, experiences become clearer, more reliable, and more valuable to users.',
  },
  {
    id: 'queueing-system',
    tag: 'Performance & Security',
    title: 'Integrated High-Volume Queueing System',
    blurb: 'A calm, predictable waiting-room experience that carried 2M+ users through high-stakes, high-traffic events.',
    discipline: 'Clear, resilient experiences designed to remain usable during high traffic, system strain, and user stress.',
    role: 'Product Designer · Operations Coordinator',
    context: 'Figma · FigJam · JavaScript & CSS',
    constraints: ['High traffic volumes', 'Users under stress', 'Non-technical stakeholders', 'Server scaling cost limits'],
    accent: 'var(--color-sky)',
    image: 'assets/proj-queueing.png',
    imageCaption: 'Virtual waiting-room flow — decision logic across scheduled and global high-volume events, paired with live throughput monitoring.',
    solution: 'An integrated external queueing system that managed high-volume traffic with a predictable, controlled flow — easing platform strain. The waiting room guided users through their place in line, expected wait times, and live updates during high-stakes, competitive transactions.',
    solutionPoints: [
      'Non-technical flow guide and queue-monitoring dashboard used to manage high-traffic events and keep system load controlled.',
    ],
    problems: [
      { who: 'The User', sub: 'Registrants on a public portal', t: 'Confusion and anxiety during high-traffic events led to frustration and abandoned transactions.' },
      { who: 'The Team', sub: 'Developers & operations', t: 'Errors and failures from high throughput required constant DevOps and operations monitoring.' },
      { who: 'The Business', sub: '', t: 'Scaling quickly for unpredictable spikes was costly; uncontrolled events risked cost and user trust.' },
    ],
    success: [
      'Users understand their place in the queue and expected wait times.',
      'A smooth, predictable experience for users and internal teams during peak traffic.',
      'Reduced frustration and improved trust during high-stakes events.',
    ],
    process: [
      'Researched user behaviour during high-stress, competitive transactions to build a queueing flow that fostered trust and reduced stress.',
      'Partnered with operations to understand throughput and the pressure events placed on DevOps and support.',
      'Designed the waiting-room UI in Figma and mapped flows in FigJam to align internal teams on queue mechanics.',
      'Built the interface in JavaScript and CSS — clearly showing queue position, wait times, and live updates.',
      'Tested real scenarios for edge cases, keeping the experience predictable for users and manageable for teams.',
    ],
    impact: [
      'Over 2 million end-users successfully navigated high-traffic events through the queueing system.',
      'Confident, calm users thanks to clear expectations and visible progress.',
      'Reduced errors and failures, with documentation easing strain on DevOps and support.',
      'Controlled flow enabled methodical scaling — reducing cost and building trust.',
    ],
    challenge: 'Balancing user needs under stress with operational strain — ensuring teams could support the system, clients, and users effectively.',
    takeaway: 'Performance is a core part of UX. Thoughtful design guides users confidently through complex, competitive transactions instead of leaving them in the dark — turning stressful moments into ones that feel clear, reliable, and trustworthy.',
  },
  {
    id: 'fundraising-payments',
    thumbIcon: 'hand-coins',
    tag: 'Financial Systems',
    title: 'Fundraising & Donations Payment Experience',
    blurb: 'A full-lifecycle redesign of viewing, creating, editing, and refunding donations — built for trust and reversibility.',
    discipline: 'High-stakes financial workflows made clear, trustworthy, and error-resistant — making donating and fundraising a breeze.',
    role: 'Product Designer',
    context: 'Figma · Payments · B2B2C',
    constraints: ['Compliance & receipting weight', 'Recurring vs. one-time logic', 'Staff under time pressure', 'Legacy transaction states'],
    accent: 'var(--color-sage)',
    image: 'assets/proj-fundraising-payments.jpeg',
    imageCaption: 'Edit a Donation modal — payment method, fund, campaign, and dedication details in one consistent, auditable structure.',
    solution: 'A redesign of the full donation lifecycle — viewing, creating, editing, and removing gifts — with clearer action labels, a consistent modal structure, and the right information (amount, donor intent, transaction state) surfaced at the right moment.',
    solutionPoints: [
      'Refund editing and status indicators reworked so refund workflows are auditable and reliable under time pressure.',
      'Distinct status patterns separate one-time from recurring gifts, resolving downstream reporting and receipting confusion.',
      'Declined-payment messaging balances clarity with restraint — enough for users to self-correct without eroding trust.',
    ],
    problems: [
      { who: 'The Donor', sub: '', t: 'Confusing transaction states and refund status made it hard to know what had actually happened to a gift.' },
      { who: 'Staff', sub: 'Fundraising & finance', t: 'Refunds, recurring gifts, and receipts were error-prone and hard to audit under time pressure.' },
      { who: 'The Business', sub: '', t: 'Receipting carries real compliance weight; unclear flows increased support burden and risk.' },
      { who: 'Edge-case Donors', sub: 'Tribute & dedication giving', t: 'Specialized giving flows had feature gaps, leaving some donors as an afterthought.' },
    ],
    success: [
      'A coherent donation lifecycle where every action and state is legible.',
      'Auditable, reversible refund and recurring-gift workflows.',
      'Reduced support burden around receipting and declined payments.',
    ],
    process: [
      'Mapped the full arc of a donation — view, create, edit, remove — to find where state and intent got lost.',
      'Standardized modal structure (header, body, details, footer) and action labels across giving flows.',
      'Designed clearer status indicators for refunds, recurring gifts, and declined payments.',
      'Closed feature gaps for dedication and tribute giving so edge-case donors were first-class.',
      'Contributed to payment-record IA — cardholder and payment-method presentation, dashboard structure — for teams managing records at scale.',
    ],
    impact: [
      'Clearer financial outcomes and transaction states for donors and staff.',
      'More auditable, reliable refund and receipting workflows.',
      'Fewer support escalations around declined payments and recurring gifts.',
      'Specialized giving flows brought up to the standard of the core experience.',
    ],
    challenge: 'Designing for trust and reversibility across a lifecycle where accuracy, compliance, and time pressure all compete.',
    takeaway: 'In financial UX, confidence comes from reversibility and legible state. When people can always see what happened and undo what went wrong, high-stakes transactions stop feeling risky.',
  },
  {
    id: 'registration-mobile',
    tag: 'Registration',
    title: 'Mobile-First Registration Experience',
    blurb: 'Meeting registrants on the devices they actually use — a systemic usability pass across the registration portal.',
    discipline: 'Reducing friction in high-volume, time-sensitive registration journeys by designing for how — and where — registrants actually show up.',
    role: 'Product Designer',
    context: 'Figma · Registration portal · Mobile-first',
    constraints: ['High-volume, time-sensitive journeys', 'Mobile & desktop parity', 'legacy flows and user habits', 'Scope spanning many screens and flows'],
    accent: 'var(--color-sky)',
    image: 'assets/proj-registration-portal.jpeg',
    imageCaption: 'Registration portal — step-by-step registration flow with clear progress tracking.',
    solution: 'A systemic mobile usability pass across the registration portal — tightening alerts, spacing, card layouts, and scroll behavior so the experience holds up on the devices registrants actually use, not just desktop.',
    solutionPoints: [
      'Alerts, spacing, and card layouts standardized for consistent, scannable mobile presentation.',
      'Empty-cart scenarios redesigned so users are not left stuck mid-task on smaller screens.',
      'Banner, warning, and scroll behavior refined for continuity across the mobile journey.',
    ],
    problems: [
      { who: 'The User', sub: 'Registrants', t: 'Inconsistent alerts, spacing, and card layouts made the portal harder to scan and use on mobile.' },
      { who: 'The User', sub: 'Mid-task', t: 'Empty-cart states created dead-ends and anxiety during time-sensitive registration on smaller screens.' },
      { who: 'The Team', sub: '', t: 'Desktop-first patterns didn’t hold up once ported to mobile, creating rework and inconsistency.' },
    ],
    success: [
      'Consistent hierarchy, spacing, and alerts across mobile and desktop.',
      'Continuity through empty states, regardless of device.',
      'A ready-to-build backlog of discrete, implementable improvements.',
    ],
    process: [
      'Ran a usability pass across alerts, spacing, card layouts, and mobile presentation.',
      'Redesigned empty-cart scenarios so users are not left stuck mid-task.',
      'Refined banner and warning treatments and scroll behavior for continuity across the journey.',
      'Broke the redesign into discrete, implementable stories for delivery.',
    ],
    impact: [
      'More consistent, scannable hierarchy across the registration portal.',
      'Fewer dead-ends through redesigned empty states.',
      'A ready-to-build backlog of discrete, implementable improvements.',
      'A portal that holds up as well on mobile as it does on desktop.',
    ],
    challenge: 'Spanning dozens of systemic polish fixes across mobile and desktop without losing coherence across the journey.',
    takeaway: 'Meeting registrants where they are means designing for the device in their hand, not retrofitting desktop patterns. Small, systemic fixes compound into a portal that feels coherent everywhere.',
  },
  {
    id: 'waitlist-decision',
    thumbIcon: 'route',
    tag: 'Registration',
    title: 'Guided Waitlist Decision Flow',
    blurb: 'Turning an ambiguous decision point into a guided two-path flow for registrants choosing what to do when a dependent lands on the waitlist.',
    discipline: 'Reducing friction in high-stakes, time-sensitive registration moments — where a confusing decision can cost a family their spot.',
    role: 'Product Designer',
    context: 'Figma · Registration portal · Waitlist logic',
    constraints: ['Ambiguous decision points', 'High-volume, time-sensitive journeys', 'Multiple dependents per registration', 'Legacy waitlist logic'],
    accent: 'var(--color-sky)',
    image: 'assets/proj-waitlist-decision.jpeg',
    imageCaption: 'The guided waitlist decision — "What matters most to Bryanna?" — with clear session-vs-session-option requirement handling.',
    solution: 'A restructured waitlist flow that replaced a confusing decision point with a guided two-path model and clearer requirement handling — so a registrant with a waitlisted dependent always knows what to do next.',
    solutionPoints: [
      'Waitlist ambiguity resolved into a legible two-path flow with explicit requirement handling.',
      'Reassurance-focused copy for time-sensitive queue and waiting states.',
      'Clear handling for registrations with multiple dependents in different queue states.',
    ],
    problems: [
      { who: 'The Registrant', sub: '', t: 'A confusing waitlist decision point left registrants unsure what to do or what was required when a dependent was waitlisted.' },
      { who: 'The Registrant', sub: 'Multiple dependents', t: 'Registering more than one dependent at once made mixed waitlist/confirmed states even harder to parse.' },
      { who: 'The Team', sub: '', t: 'Ambiguous decision logic created support burden from confused registrants mid-registration.' },
    ],
    success: [
      'A guided, legible waitlist flow that removes ambiguity.',
      'Clear next steps for registrants with one or more waitlisted dependents.',
      'Reduced anxiety during time-sensitive queue and waiting moments.',
    ],
    process: [
      'Untangled the waitlist decision point and restructured it into a guided two-path model.',
      'Mapped how the decision changes when a registration includes multiple dependents in different states.',
      'Wrote reassurance-focused copy for time-sensitive queue and waiting states.',
      'Validated the flow against real registration scenarios with mixed waitlist outcomes.',
    ],
    impact: [
      'Ambiguity turned into a clear, guided flow registrants can complete confidently.',
      'Fewer dead-ends and less confusion for registrations with multiple dependents.',
      'Reduced support burden from waitlist-related confusion.',
    ],
    challenge: 'Designing a single decision point that stays clear whether a registrant has one dependent or several, each in a different queue state.',
    takeaway: 'The clearest flows account for the messy real case, not just the best-case path with a single dependent. Designing for multiple dependents in mixed states is what made the guided flow actually hold up.',
  },
  {
    id: 'auth-security',
    thumbIcon: 'shield-check',
    tag: 'Security',
    title: 'Authentication & Security Recovery',
    blurb: 'Designing recoverable moments in high-anxiety login and security flows — solving the real problem, not just the symptom.',
    discipline: 'Where security infrastructure and UX intersect — designing calm, recoverable moments in high-anxiety flows.',
    role: 'Product Designer',
    context: 'Figma · Authentication · Security',
    constraints: ['High-anxiety failure states', 'Infrastructure-driven constraints', 'Lockout & escalation risk', 'Detection vs. prevention tradeoffs', 'PCI compliance for password resets'],
    accent: 'var(--color-sky)',
    image: 'assets/proj-auth-security.jpeg',
    imageCaption: 'Email verification recovery — a clear "Account Verified" confirmation guiding registrants straight back to sign-in.',
    solution: 'A set of recovery-focused designs across authentication and security — starting from the insight that login failures are not always credential errors, and that infrastructure decisions have direct user-facing consequences.',
    solutionPoints: [
      'A "Wrong URL?" recovery prompt for users in the wrong environment — solving the real problem, not just the credential symptom.',
      'MFA setup fixes for missing controls and formatting issues, reducing lockout risk and support escalations.',
      'Research into firewall detection-vs-prevention mode and its user-facing implications — false positives, blocked access.',
      'Automated account locking based on fraud-risk signals, paired with manual tools for support staff to block or reactivate accounts.',
      'Identity verification built into the password-reset flow, aligned with PCI compliance requirements.',
    ],
    problems: [
      { who: 'The User', sub: 'Locked out', t: 'Login failures were treated as credential errors even when the real issue was being in the wrong environment.' },
      { who: 'The User', sub: 'MFA setup', t: 'Missing controls and formatting issues in multi-factor setup increased lockout risk.' },
      { who: 'The Business', sub: '', t: 'Shifting a security system from detection to prevention risked false positives and blocked legitimate access.' },
      { who: 'The Business', sub: 'Fraud risk', t: 'Compromised or suspicious accounts needed fast, automatic locking based on fraud signals — with no reliable manual path to block or reactivate accounts when automation wasn’t enough.' },
      { who: 'The User', sub: 'Password reset', t: 'Password resets lacked strong identity verification and PCI-aligned handling, creating both a security gap and compliance risk.' },
    ],
    success: [
      'Recoverable login failures that guide users to the real fix.',
      'Lower lockout risk and fewer support escalations in MFA.',
      'Infrastructure decisions evaluated for real user consequences.',
      'Fast, automatic containment of compromised accounts with a reliable manual fallback.',
      'Password resets that meet PCI compliance without adding user friction.',
    ],
    process: [
      'Reframed login failure as more than a credential problem — identifying the wrong-environment case.',
      'Designed a recovery path prompting users who reached the wrong URL.',
      'Fixed missing controls and formatting gaps in multi-factor setup.',
      'Investigated the user-facing implications of moving a firewall from detection to prevention mode.',
      'Designed automated account-locking logic triggered by fraud-risk signals, paired with manual block/reactivate tools for support staff to handle edge cases.',
      'Added identity verification to the password-reset flow and aligned it with PCI compliance requirements.',
    ],
    impact: [
      'Users in the wrong environment recover instead of hitting a dead-end.',
      'Reduced lockout risk and MFA-related support escalations.',
      'A clear connection drawn between an infrastructure decision and real user consequences.',
      'Faster containment of compromised accounts through automatic, fraud-based locking.',
      'Support staff gained reliable manual tools to block or reactivate accounts when automation wasn’t enough.',
      'Password resets now meet PCI compliance with stronger identity verification.',
    ],
    challenge: 'Designing calm, recoverable experiences on top of security infrastructure that is not primarily built around the user.',
    takeaway: 'Security and UX are not opposites. The best recovery designs solve the real problem behind a failure — often an infrastructure or environment issue — rather than just the symptom the user first sees.',
  },
  {
    id: 'forms-strategy',
    thumbIcon: 'file-check-2',
    tag: 'Strategy',
    title: 'Forms & Staff Workflow Strategy',
    blurb: 'A structured evaluation of form and e-signature tooling — and a clearer source-of-truth model for staff form data.',
    discipline: 'Strategic, systems-level solution design and vendor evaluation for internal tooling — analyzing downstream operational impact, not just features.',
    role: 'Product Designer · Solution Design',
    context: 'Vendor evaluation · Systems design · Integration',
    constraints: ['Fragmentation risk across tools', 'Iframe integration limits', 'API sync requirements', 'Real staff application volume'],
    accent: 'var(--color-teal)',
    image: 'assets/proj-forms-strategy.jpeg',
    imageCaption: 'Client volume by band — the real usage data behind the tooling and workflow strategy recommendation.',
    solution: 'A structured evaluation of digital form and e-signature tools — assessed not as a feature comparison but as an analysis of downstream operational impact — paired with a clearer model for the source of truth for staff form data.',
    solutionPoints: [
      'Tools evaluated against configurability, embedded experience, integration approach, and data synchronization.',
      'A defined "source of truth" model addressing fragmentation across configuration, capture, and sync.',
      'Strategy grounded in real usage data (staff application volume) and technical constraints (iframe, API sync).',
    ],
    problems: [
      { who: 'Staff', sub: '', t: 'Form data was fragmented across configuration, capture, and sync, with no clear source of truth.' },
      { who: 'The Business', sub: '', t: 'Choosing tooling on features alone risked downstream operational and integration problems.' },
      { who: 'Engineering', sub: '', t: 'Iframe integration and API sync constraints shaped what was actually feasible.' },
    ],
    success: [
      'A tooling recommendation grounded in operational impact, not feature lists.',
      'A clear source-of-truth model for staff form data.',
      'Alignment between strategy, real usage data, and technical constraints.',
    ],
    process: [
      'Defined evaluation criteria: configurability, embedded experience, integration approach, data sync.',
      'Compared tools on downstream operational impact rather than surface features.',
      'Modeled what should be the source of truth to reduce fragmentation risk.',
      'Grounded the strategy in staff application volume and integration constraints (iframe, API).',
    ],
    impact: [
      'A defensible, systems-level tooling decision.',
      'Reduced fragmentation risk through a clear data-ownership model.',
      'Strategy connected directly to real usage and technical reality.',
    ],
    challenge: 'Evaluating tooling for long-term operational impact and data integrity, not just the strongest feature demo.',
    takeaway: 'Solution design is UX. Choosing where data lives and how tools integrate shapes the staff experience as much as any screen — and getting it right prevents fragmentation before it starts.',
  },
  {
    id: 'outbox',
    thumbIcon: 'send',
    tag: 'Communication',
    title: 'Outbox — Client Communications Tool',
    blurb: 'Faster scanning and clearer status for the tool staff use to send and track communications to the people they serve.',
    discipline: 'Staff-facing tooling whose improvements directly shape the client-facing communication experience — usability with downstream customer impact.',
    role: 'Product Designer',
    context: 'Figma · Staff tooling · Reporting',
    constraints: ['High volume of outgoing communications', 'Staff usability ↔ customer impact', 'Status legibility (sent/pending/failed)', 'Reporting & visibility needs'],
    accent: 'var(--color-sage)',
    image: 'assets/proj-outbox.jpeg',
    imageCaption: 'Outbox records — searchable, filterable outgoing communications with instantly legible sent/paused/scheduled status.',
    solution: 'A redesign of the Outbox — the interface staff use to send and track communications to registrants — improving how large volumes of outgoing messages are scanned, acted on, and verified, with clearer status and a path toward reporting.',
    solutionPoints: [
      'Header, table rows, and action dropdowns reworked so staff scan and act on volume faster.',
      'Progress and status indicators redesigned so sent, pending, and failed states are instantly legible.',
      'Individual message-viewing improved for reviewing exactly what a registrant received.',
    ],
    problems: [
      { who: 'Staff', sub: 'High volume', t: 'Scanning and acting on large volumes of outgoing communications was slow and cluttered.' },
      { who: 'Staff', sub: 'Status', t: 'It was hard to tell at a glance whether a communication had sent, was pending, or failed.' },
      { who: 'Registrants', sub: 'Downstream', t: 'Weak staff tooling directly affected what registrants received and when.' },
    ],
    success: [
      'Staff scan and act on outgoing communications quickly.',
      'Instantly legible sent, pending, and failed status.',
      'Confidence in reviewing exactly what was sent to a registrant.',
    ],
    process: [
      'Reworked the Outbox header, table rows, and action dropdowns for faster scanning.',
      'Redesigned progress and status indicators for clear delivery state.',
      'Improved the individual message-viewing experience.',
      'Contributed to reporting research — extending the work into communication-activity visibility over time.',
    ],
    impact: [
      'Faster, less error-prone handling of high communication volume.',
      'Clear delivery status reduces uncertainty and rework.',
      'Better staff tooling improves the client-facing communication experience directly.',
    ],
    challenge: 'Making a "boring but critical" internal tool measurably better while keeping the downstream customer impact in view.',
    takeaway: 'Staff-facing tools are customer-facing by proxy. Improving how a team sends and tracks communications changes what people actually receive — internal usability and external experience are the same problem.',
  },
  {
    id: 'ai-leadership',
    thumbIcon: 'sparkles',
    tag: 'AI Leadership',
    title: 'Leading AI Adoption Across Product Teams',
    blurb: 'Moving three product teams from AI-skeptical to AI-fluent — leading organizational change in how teams work, not just an artifact.',
    discipline: 'Leading responsible, mature AI adoption across product teams — organizational change and process redesign, grounded in firsthand practice.',
    role: 'AI Transformation Lead · Product Designer',
    context: 'Enablement · SDLC redesign · Change management',
    constraints: ['AI-skeptical starting point', 'Responsible, embedded use over novelty', 'Cross-team, cross-brand differences', 'Adoption as behavior change, not a one-off'],
    accent: 'var(--color-teal)',
    image: 'assets/proj-ai-leadership.jpeg',
    imageCaption: 'A custom Claude Code skill built to scope and audit feature conversions — AI embedded directly into the design workflow.',
    solution: 'A dual role as both trainer and practitioner — guiding three product teams from limited or skeptical AI use to confident, embedded adoption, while applying AI-native workflows to my own product work so the guidance stayed grounded in firsthand use.',
    solutionPoints: [
      'Three product teams moved end-to-end from AI-skeptical to AI-fluent — a genuine behavior-change outcome.',
      'AI-assisted SDLC redesign: stronger acceptance criteria, clearer triage, milestone and roadmap structure, and a connected documentation hub.',
      'An AI-assisted workflow that drafts requirements from existing story, business-case, and delivery context — cutting documentation overhead.',
    ],
    problems: [
      { who: 'Product Teams', sub: '', t: 'Limited or skeptical AI use meant teams were not seeing where it could meaningfully improve their work.' },
      { who: 'The Process', sub: 'SDLC', t: 'Ambiguous acceptance criteria, unclear triage, and scattered documentation slowed delivery.' },
      { who: 'The Org', sub: '', t: 'Adoption risked being novelty-driven rather than responsible, embedded, and outcome-focused.' },
    ],
    success: [
      'Teams confidently embedding AI into day-to-day workflows.',
      'A more legible SDLC — testable stories, clearer priorities, connected docs.',
      'Responsible use focused on better outcomes, not AI for its own sake.',
    ],
    process: [
      'Held a dual trainer and practitioner role so guidance was grounded in firsthand AI-native work.',
      'Trained three product teams end-to-end from skeptical to fluent AI use.',
      'Translated a process-improvement roadmap into practical, AI-assisted workflow changes — acceptance criteria, triage models, milestone structure, and a connected documentation hub.',
      'Shaped an AI-assisted workflow drafting requirements from existing story, business-case, and delivery context.',
      'Ran recurring feedback and adoption check-ins, feeding friction points back into the rollout.',
    ],
    impact: [
      'Three teams moved from AI-skeptical to AI-fluent as a lasting behavior change.',
      'Reduced documentation overhead through AI-assisted requirement drafting.',
      'A clearer, more testable delivery process with connected context.',
      'Enablement recommendations that generalize across teams and brands.',
    ],
    challenge: 'Driving responsible, embedded AI adoption as real behavior change — across teams with different workflows — rather than a one-time training event.',
    takeaway: 'Leading AI adoption is change management, not tooling. Pairing hands-on practice with training, feedback loops, and process redesign is what moves teams from skeptical to fluent — and keeps the focus on better outcomes over novelty.',
  },
  {
    id: 'research-documentation',
    thumbIcon: 'search',
    tag: 'Research & Practice',
    title: 'Research, Analysis & Documentation',
    blurb: 'Using data synthesis and clear writing to move from raw backlog to actionable insight — the connective tissue beneath the case studies.',
    discipline: 'Using data and writing to drive product decisions — grounding design in behavior, and turning institutional knowledge into reusable team resources.',
    role: 'Product Designer · Research',
    context: 'Data analysis · Component audits · Documentation',
    constraints: ['Large, noisy request backlogs', 'Assumption-driven decisions', 'UI & design-system fragmentation', 'Scattered institutional knowledge'],
    accent: 'var(--color-teal)',
    image: 'assets/proj-research-documentation.jpeg',
    imageCaption: 'A searchable internal knowledge base of documented issues, tagged and filterable — institutional knowledge turned into a reusable resource.',
    solution: 'The research, analysis, and documentation practice underpinning the case studies — synthesizing user requests into themes, grounding decisions in real usage, auditing UI for inconsistency, and turning institutional knowledge into reusable resources.',
    solutionPoints: [
      'Large sets of user requests synthesized into pain-point themes — from raw backlog to actionable insight.',
      'Component and filter audits surfacing UI inconsistency and design-system fragmentation.',
      'Internal documentation for administration, security resets, onboarding, and design-role expectations.',
    ],
    problems: [
      { who: 'The Team', sub: '', t: 'A large, noisy backlog of requests obscured the real, recurring pain points.' },
      { who: 'The Product', sub: '', t: 'Decisions risked being driven by assumption rather than actual feature usage.' },
      { who: 'The System', sub: '', t: 'UI inconsistency went unmeasured, and knowledge lived only in people\'s heads.' },
    ],
    success: [
      'Actionable pain-point themes drawn from raw request data.',
      'Design decisions grounded in real behavior, not assumption.',
      'Reusable documentation that outlives any single project.',
    ],
    process: [
      'Synthesized large sets of user requests into clear pain-point themes.',
      'Analyzed feature usage to ground design decisions in actual behavior.',
      'Ran component and filter audits to surface inconsistency and fragmentation.',
      'Improved data-quality patterns in form inputs (phone, titles, dates) for better reporting.',
      'Authored documentation on administration, security resets, onboarding, and design-role expectations.',
    ],
    impact: [
      'Raw backlog turned into prioritized, actionable insight.',
      'Design grounded in usage data rather than assumption.',
      'Institutional knowledge captured as reusable team resources.',
      'Better input data quality with downstream reporting and support benefits.',
    ],
    challenge: 'Making research and documentation visible and valued as the foundation beneath more obviously designed work.',
    takeaway: 'Research and writing are design. The synthesis, audits, and documentation are what let every other case study stand on evidence rather than assumption.',
  },
];
